#Open Permit
#Check Balance
    #if paid continue
    #else Ask Leila before moving forward
#Determine when the permit expires
    #if within expiration then do Extension
    #elif outside expiration then do Reinstatement
#Add note (mm/dd/yyyy     nth EXTENSION/REINSTATEMENT) to work description
    #to identify the nth extension go to fees or check work description
#Add Fee
    #Select Fee Schedule: BLD_BUILDING_GENERAL
    #After Fee is added, invoice it.
#Send Email
#Push Work Flow
#When Fee has been paid, Upload doc with bottom filled out.

